apiVersion: v1
kind: Service
metadata:
  name: my-blog
  labels:
    app: my-blog
spec:
  type: LoadBalancer
  selector:
    app: my-blog
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-blog
  template:
    metadata:
      labels:
        app: my-blog
    spec:
      containers:
        - name: my-blog
          image: 427243519225.dkr.ecr.ap-southeast-2.amazonaws.com/my_blog:latest